-- begin FINEXPRONEW_WORKER
alter table FINEXPRONEW_WORKER add constraint FK_FINEXPRONEW_WORKER_ON_DEPARTMENT foreign key (DEPARTMENT_ID) references FINEXPRONEW_DEPARTMENT(ID)^
create unique index IDX_FINEXPRONEW_WORKER_UNIQ_EMAIL on FINEXPRONEW_WORKER (EMAIL)^
create index IDX_FINEXPRONEW_WORKER_ON_DEPARTMENT on FINEXPRONEW_WORKER (DEPARTMENT_ID)^
-- end FINEXPRONEW_WORKER
-- begin FINEXPRONEW_DOCUMENT
alter table FINEXPRONEW_DOCUMENT add constraint FK_FINEXPRONEW_DOCUMENT_ON_WORKER foreign key (WORKER_ID) references FINEXPRONEW_WORKER(ID)^
create index IDX_FINEXPRONEW_DOCUMENT_ON_WORKER on FINEXPRONEW_DOCUMENT (WORKER_ID)^
-- end FINEXPRONEW_DOCUMENT
-- begin FINEXPRONEW_DEPARTMENT
alter table FINEXPRONEW_DEPARTMENT add constraint FK_FINEXPRONEW_DEPARTMENT_ON_HEAD foreign key (HEAD_ID) references FINEXPRONEW_WORKER(ID)^
create unique index IDX_FINEXPRONEW_DEPARTMENT_UNIQ_NAME on FINEXPRONEW_DEPARTMENT (NAME)^
create index IDX_FINEXPRONEW_DEPARTMENT_ON_HEAD on FINEXPRONEW_DEPARTMENT (HEAD_ID)^
-- end FINEXPRONEW_DEPARTMENT
